### ISSUE TITLE
Check where app loads plugins from, don't check the import statements *text*

### ISSUE THREAD

**Issue by amarchen** [sailfish-sdk/sdk-harbour-rpmvalidator#32]
At the moment harbour requires my QML files to import everything via ```import harbour.mycoolapp.org.nemo.whatevernemopluginibundlein```

That is not good enough as it:

1. Forces you to modify the original plugin. At least its QML dir, also there can be some ASSERTs and checks that verify the plugin name (I've seen at least two nemo plugins checking it with ASSERTs)

2. Prevents me from having QMLs for different platforms in one package

Check that app uses bundled-in libs/plugins only should probably be performed. However, it should be checked not by analysing QML text (easy to check, but checks wrong stuff), but by analyzing what app is actually loading (e.g. via strace tool).

RPM checker's warning could still be helpful not to forget to pay attention to it, but it shouldn't fail the validation.

**Comment by d0b3rm4n** [comment]
I close this, rpmvalidator as the names says, validates the RPM and not what happens during runtime. If there is a need for a tool which checks the Harbour apps during runtime, then this will most likely be in it's own git repo and not be part of **rpm**-validator.
