### ISSUE TITLE
QtQuick 2.2

### ISSUE THREAD

**Issue by buschmann23** [sailfish-sdk/sdk-harbour-rpmvalidator#68]
The Sailfish Silica Reference in the current SDK (1509) says, that one should import QtQuick 2.2, also all examples there are using QtQuick 2.2. But When checking the rpm with the validator it throws errors about not allowed imports of QtQuick 2.2.

**Comment by d0b3rm4n** [comment]
@buschmann23 thx for pointing out. I'll try to bring the change still into 2.0.0 release, but no promise :)
