### ISSUE TITLE
validating an i486 package throws a libgcc error

### ISSUE THREAD

**Issue by Armadill0** [sailfish-sdk/sdk-harbour-rpmvalidator#71]
I tried to validate harbour-tasklist-1.8.9 as i486 release and got the following error:
    ERROR [libgcc_s.so.1(GLIBC_2.0)] Cannot require shared library: 'libgcc_s.so.1(GLIBC_2.0)'

The packages have been built with the lastest SDK (1.1.9). You can find them here: https://github.com/Armadill0/harbour-tasklist/releases/tag/1.8.9

**Comment by d0b3rm4n** [comment]
This is addressed in pull-request #70 in commit 5d12bc4, so I close it.

**Comment by d0b3rm4n** [comment]
@Armadill0 in the meantime, submit your application already to Harbour, it will not be rejected, based on that rpmvalidator error.

**Comment by Armadill0** [comment]
@d0b3rm4n Thanks for the fast reply. I already submitted the app and linked this issue. :smile:
